# Routing config: pool defaults and rules. Backend names refer to backends.yaml.
# Правила покрывают: exact, list, prefix, regex, user, default.

defaults:
  pool_size: 20

routing:
  # Точное совпадение базы
  - database: reporting
    backend: replica

  # Список баз → primary
  - database: [main, app, postgres]
    backend: primary

  # Префикс (glob) analytics_*
  - database: "analytics_*"
    backend: replica

  # Регулярное выражение: reporting* или dwh_* (полное совпадение строки)
  - database: "~ ^(reporting|dwh)_.*"
    backend: replica

  # По пользователю: reporting_reader → replica (для тестов)
  - user: reporting_reader
    backend: replica

  # Всё остальное → primary
  - default: true
    backend: primary
